[package]
name = "linears"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
tempfile = "3.3.0"

[build-dependencies]
bindgen = "0.72"
cc = "1.0"
git2 = "0.15.0"
tempfile = "3.3.0"

# Force newer clang-sys to fix libclang loading
clang-sys = "1.8"
