/* automatically generated by rust-bindgen 0.72.1 */

pub const LIBLINEAR_VERSION: u32 = 245;
unsafe extern "C" {
    pub static mut liblinear_version: ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct feature_node {
    pub index: ::std::os::raw::c_int,
    pub value: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of feature_node"][::std::mem::size_of::<feature_node>() - 16usize];
    ["Alignment of feature_node"][::std::mem::align_of::<feature_node>() - 8usize];
    ["Offset of field: feature_node::index"][::std::mem::offset_of!(feature_node, index) - 0usize];
    ["Offset of field: feature_node::value"][::std::mem::offset_of!(feature_node, value) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct problem {
    pub l: ::std::os::raw::c_int,
    pub n: ::std::os::raw::c_int,
    pub y: *mut f64,
    pub x: *mut *mut feature_node,
    pub bias: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of problem"][::std::mem::size_of::<problem>() - 32usize];
    ["Alignment of problem"][::std::mem::align_of::<problem>() - 8usize];
    ["Offset of field: problem::l"][::std::mem::offset_of!(problem, l) - 0usize];
    ["Offset of field: problem::n"][::std::mem::offset_of!(problem, n) - 4usize];
    ["Offset of field: problem::y"][::std::mem::offset_of!(problem, y) - 8usize];
    ["Offset of field: problem::x"][::std::mem::offset_of!(problem, x) - 16usize];
    ["Offset of field: problem::bias"][::std::mem::offset_of!(problem, bias) - 24usize];
};
pub const L2R_LR: _bindgen_ty_1 = 0;
pub const L2R_L2LOSS_SVC_DUAL: _bindgen_ty_1 = 1;
pub const L2R_L2LOSS_SVC: _bindgen_ty_1 = 2;
pub const L2R_L1LOSS_SVC_DUAL: _bindgen_ty_1 = 3;
pub const MCSVM_CS: _bindgen_ty_1 = 4;
pub const L1R_L2LOSS_SVC: _bindgen_ty_1 = 5;
pub const L1R_LR: _bindgen_ty_1 = 6;
pub const L2R_LR_DUAL: _bindgen_ty_1 = 7;
pub const L2R_L2LOSS_SVR: _bindgen_ty_1 = 11;
pub const L2R_L2LOSS_SVR_DUAL: _bindgen_ty_1 = 12;
pub const L2R_L1LOSS_SVR_DUAL: _bindgen_ty_1 = 13;
pub const ONECLASS_SVM: _bindgen_ty_1 = 21;
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct parameter {
    pub solver_type: ::std::os::raw::c_int,
    pub eps: f64,
    pub C: f64,
    pub nr_weight: ::std::os::raw::c_int,
    pub weight_label: *mut ::std::os::raw::c_int,
    pub weight: *mut f64,
    pub p: f64,
    pub nu: f64,
    pub init_sol: *mut f64,
    pub regularize_bias: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of parameter"][::std::mem::size_of::<parameter>() - 80usize];
    ["Alignment of parameter"][::std::mem::align_of::<parameter>() - 8usize];
    ["Offset of field: parameter::solver_type"]
        [::std::mem::offset_of!(parameter, solver_type) - 0usize];
    ["Offset of field: parameter::eps"][::std::mem::offset_of!(parameter, eps) - 8usize];
    ["Offset of field: parameter::C"][::std::mem::offset_of!(parameter, C) - 16usize];
    ["Offset of field: parameter::nr_weight"]
        [::std::mem::offset_of!(parameter, nr_weight) - 24usize];
    ["Offset of field: parameter::weight_label"]
        [::std::mem::offset_of!(parameter, weight_label) - 32usize];
    ["Offset of field: parameter::weight"][::std::mem::offset_of!(parameter, weight) - 40usize];
    ["Offset of field: parameter::p"][::std::mem::offset_of!(parameter, p) - 48usize];
    ["Offset of field: parameter::nu"][::std::mem::offset_of!(parameter, nu) - 56usize];
    ["Offset of field: parameter::init_sol"][::std::mem::offset_of!(parameter, init_sol) - 64usize];
    ["Offset of field: parameter::regularize_bias"]
        [::std::mem::offset_of!(parameter, regularize_bias) - 72usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct model {
    pub param: parameter,
    pub nr_class: ::std::os::raw::c_int,
    pub nr_feature: ::std::os::raw::c_int,
    pub w: *mut f64,
    pub label: *mut ::std::os::raw::c_int,
    pub bias: f64,
    pub rho: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of model"][::std::mem::size_of::<model>() - 120usize];
    ["Alignment of model"][::std::mem::align_of::<model>() - 8usize];
    ["Offset of field: model::param"][::std::mem::offset_of!(model, param) - 0usize];
    ["Offset of field: model::nr_class"][::std::mem::offset_of!(model, nr_class) - 80usize];
    ["Offset of field: model::nr_feature"][::std::mem::offset_of!(model, nr_feature) - 84usize];
    ["Offset of field: model::w"][::std::mem::offset_of!(model, w) - 88usize];
    ["Offset of field: model::label"][::std::mem::offset_of!(model, label) - 96usize];
    ["Offset of field: model::bias"][::std::mem::offset_of!(model, bias) - 104usize];
    ["Offset of field: model::rho"][::std::mem::offset_of!(model, rho) - 112usize];
};
unsafe extern "C" {
    pub fn train(prob: *const problem, param: *const parameter) -> *mut model;
}
unsafe extern "C" {
    pub fn cross_validation(
        prob: *const problem,
        param: *const parameter,
        nr_fold: ::std::os::raw::c_int,
        target: *mut f64,
    );
}
unsafe extern "C" {
    pub fn find_parameters(
        prob: *const problem,
        param: *const parameter,
        nr_fold: ::std::os::raw::c_int,
        start_C: f64,
        start_p: f64,
        best_C: *mut f64,
        best_p: *mut f64,
        best_score: *mut f64,
    );
}
unsafe extern "C" {
    pub fn predict_values(
        model_: *const model,
        x: *const feature_node,
        dec_values: *mut f64,
    ) -> f64;
}
unsafe extern "C" {
    pub fn predict(model_: *const model, x: *const feature_node) -> f64;
}
unsafe extern "C" {
    pub fn predict_probability(
        model_: *const model,
        x: *const feature_node,
        prob_estimates: *mut f64,
    ) -> f64;
}
unsafe extern "C" {
    pub fn save_model(
        model_file_name: *const ::std::os::raw::c_char,
        model_: *const model,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn load_model(model_file_name: *const ::std::os::raw::c_char) -> *mut model;
}
unsafe extern "C" {
    pub fn get_nr_feature(model_: *const model) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn get_nr_class(model_: *const model) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn get_labels(model_: *const model, label: *mut ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn get_decfun_coef(
        model_: *const model,
        feat_idx: ::std::os::raw::c_int,
        label_idx: ::std::os::raw::c_int,
    ) -> f64;
}
unsafe extern "C" {
    pub fn get_decfun_bias(model_: *const model, label_idx: ::std::os::raw::c_int) -> f64;
}
unsafe extern "C" {
    pub fn get_decfun_rho(model_: *const model) -> f64;
}
unsafe extern "C" {
    pub fn free_model_content(model_ptr: *mut model);
}
unsafe extern "C" {
    pub fn free_and_destroy_model(model_ptr_ptr: *mut *mut model);
}
unsafe extern "C" {
    pub fn destroy_param(param: *mut parameter);
}
unsafe extern "C" {
    pub fn check_parameter(
        prob: *const problem,
        param: *const parameter,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn check_probability_model(model: *const model) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn check_regression_model(model: *const model) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn check_oneclass_model(model: *const model) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn set_print_string_function(
        print_func: ::std::option::Option<
            unsafe extern "C" fn(arg1: *const ::std::os::raw::c_char),
        >,
    );
}
